import { Inter } from "next/font/google";
import "./globals.css";
import FooterSection from "./Components/FooterSection";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {

 //data-theme="light"
  return (
    <html lang="en"  >
      <body className={inter.className}>
      {children}
      {/* <FooterSection/> */}
      </body>
     
    </html>
  );
}
